### ISSUE TITLE
feature: vocabulary directory folder structure 

### ISSUE THREAD

**Issue by markdoerr** [nfdi4cat/voc4cat-tool#181]
Since the vocabulary folder, containing one turtle file per concept, will grow quite large,
I would suggest a hierarchical structure, either creating a folder with the first letter of the concept's prefLabel or using SKOS collections as containers.

**Comment by dalito** [comment]
Thanks for the report!

**Comment by dalito** [comment]
I suggest to keep the flat "structure" until the file number becomes a real problem. To find the specific turtle file you are interested in, I think you will hardly ever try to scroll to the specific file but always use a file search feature (on GitHub or in your editor). In this case a larger number of files is no problem. Even with 10000 files the matching file is shown instantly.

If we ever need to split to multiple folders, we should probably split by ID and name the folders accordingly, e.g. `0000001-0001000`, `0001001-0002000`, ...

**Comment by dalito** [comment]
I am closing this now. We can re-open if the number of files becomes an annoyance.
