### ISSUE TITLE
feature (template): Collection column in Concepts tab

### ISSUE THREAD

**Issue by markdoerr** [nfdi4cat/voc4cat-tool#182]
**Collections** are a nice way to loosely structure concepts in SKOS (one concept can belong to several **Collections**)
In the current template version, one needs to enumerate every concept in a comma separated list of **Member IRIs** in the **Collection tab**. This is very tedious and cumbersome.
A simpler approach would be to add a "Collections" column in the **Concepts** table. In that case, common spreadsheets suggest previously entered collection names as auto-completions, which simplifies input and reduces errors by typos.

**Comment by dalito** [comment]
@markdoerr Please have a look at #124 which has a draft for a new Excel table structure. If I understand you correctly it matches what you propose here.

**Comment by markdoerr** [comment]
Thanks for the hint, @dalito,
yes indeed, #124 is a good collection of improvements - I also agree with the order of priority :)
Looking forward to test the new table structure, once it is implemented.
