### ISSUE TITLE
question (template): how should multiple "Source Vocab URIs" be entered ?

### ISSUE THREAD

**Issue by markdoerr** [nfdi4cat/voc4cat-tool#183]
Sometimes definitions might origin from several sources (maybe two or three).
How should these multiple sources be entered in the "Source Vocab URI" of the **Concepts** tab ?
Is it possible to enter multiple URIs ?

**Comment by dalito** [comment]
Currently it supports just a single URL. This is "inherited" from the [vocpub](https://w3id.org/profile/vocpub)-profile.

**Comment by dalito** [comment]
Your question goes a bit into the direction of provenance which is not modeled in detail in the vocpub profile. There is another provenance issue https://github.com/nfdi4cat/voc4cat-tool/issues/122

Improving provenance would be worth improving as part of a template structure upgrade.

**Comment by markdoerr** [comment]
I agree, @dalito , 
improving  provenance information would make the vocabulary assembly more transparent, but it might requires quite some development time.
How much effort would it be to just allow a whitespace separated list of URIs in the "Source Vocab" column ? (as a quick fix)

**Comment by dalito** [comment]
> How much effort would it be to just allow a whitespace separated list of URIs in the "Source Vocab" column ? (as a quick fix)

This is easy since the same is done already for childrenIRIs. But I would address it as part of #124 or do you need it sooner?
